version: '3'
services:
  
  view:
    build: ./view
    container_name: 'test-app-view'
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./vue-project:/app/view/vue-project
    stdin_open: true
    tty: true
  
volumes:
  mysql-data:
    driver: local